In [ ]:
1. Create a null vector of size 10 but the fifth value which is 1 

In [3]:
import numpy as np
vec = np.zeros(10)
print(vec)
vec[4] = 1
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
2. Create a vector with values ranging from 10 to 49

In [8]:
import numpy as np
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
3. Reverse a vector

In [10]:
vec2 = np.flip(vec)
print(vec2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
4. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
x = np.arange(0, 9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
5. Find indices of non-zero elements from [1,2,0,0,4,0]

In [15]:
array = np.array([1, 2, 0, 0, 4, 0])
print(array)
output = np.nonzero(array)
print(output)

[1 2 0 0 4 0]
(array([0, 1, 4]),)


In [ ]:
6. Create a 3x3x3 array with random values

In [17]:
rand = np.random.random((3, 3, 3))
print(rand)

[[[0.56799698 0.70506519 0.74568569]
  [0.24090152 0.81802242 0.60200776]
  [0.06444505 0.32940958 0.37542743]]

 [[0.83338569 0.38012934 0.46184562]
  [0.45695074 0.03712217 0.95074537]
  [0.99530367 0.71243445 0.16182081]]

 [[0.09217098 0.6736608  0.47912343]
  [0.8728553  0.15821396 0.44916701]
  [0.65809979 0.63872769 0.07457021]]]


In [ ]:
Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
x = np.random.random((10, 10))
print(x)
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

[[0.06243372 0.47541709 0.98783199 0.7614822  0.28399666 0.60007087
  0.80876187 0.01337744 0.90927364 0.44381858]
 [0.91697163 0.86415422 0.3612508  0.67701759 0.38753917 0.05543384
  0.95020856 0.24652859 0.87065076 0.09772455]
 [0.18665327 0.42958894 0.4841439  0.34599866 0.4055124  0.73082191
  0.68669144 0.47051741 0.50804101 0.81721561]
 [0.8679843  0.5162655  0.04234028 0.30190276 0.0299954  0.14728968
  0.53742509 0.40566439 0.64145761 0.32413403]
 [0.51953791 0.33183401 0.40688089 0.06231476 0.25414928 0.5087918
  0.14626426 0.68942469 0.57702446 0.69878017]
 [0.0403659  0.81928867 0.67389613 0.02906749 0.29105102 0.63248825
  0.33214624 0.14828509 0.05809693 0.92728761]
 [0.19991627 0.84271209 0.98390766 0.64183604 0.85849626 0.55988553
  0.42969615 0.41612845 0.07661205 0.25170237]
 [0.31392312 0.84029002 0.01432326 0.25031501 0.57646401 0.41295258
  0.81582157 0.80504951 0.86456986 0.87538417]
 [0.93855612 0.92588237 0.76556733 0.9867879  0.00571686 0.45343335
  0.59643396 

In [ ]:
8. Create a 2d array with 1 on the border and 0 inside

In [21]:
import numpy as np
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
Create a DataFrame that looks like this:

In [24]:
import pandas as pd
import numpy as np

data = {"Apples":30, "Bananas":21}
df = pd.DataFrame(data, index = [0])
df

Apples  Bananas
0      30       21

In [26]:
#Exercise 2
data = {"Apples":[35, 41], "Bananas":[21, 34]}
df = pd.DataFrame(data, index = ["2017 Sales", "2018 Sales"])
df

Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [27]:
#Exercise 3
series = pd.Series(["4 Cups", "1 Cup", "2 Large", "1 Can"], index = ['Flour', 'Milk', 'Eggs', 'Spam'])
series

Flour     4 Cups
Milk       1 Cup
Eggs     2 Large
Spam       1 Can
dtype: object

In [28]:
#Exercise 4
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}]) 

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [30]:
#Exercise 5
import pandas as pd
data = pd.Series([0.25,0.50,0.75,1],index=['a','b','c','d'])
'a' in data


True